name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Build, Version, and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write      # to push tags and update changelog
      packages: write      # to push to ghcr.io
      issues: write        # to comment on issues
      pull-requests: write # to comment on PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
        run: npx semantic-release
